import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import {MobileSidebar, Sidebar} from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={cn(inter.className)}>
        <div className="hidden lg:block">
          <Sidebar/>
        </div>
        <div className="block lg:hidden">
          <MobileSidebar/>
        </div>
        <main className="lg:pl-60 rounded-lg  lg:pt-16">
        {children}
        </main>
        </body>
    </html>
  );
}
